fn main() {
    eprintln!("No such crate. Did you mean to use `failure`?");
    ::std::process::exit(1);
}
